site_name: Documentation
site_url: https://plymouth-neuroimaging.github.io/documentation/
nav:
  - Home: index.md
  - Getting start: getting_start.md
  - Features: features.md
  - Development details: development_details.md

theme: readthedocs
